apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels: #label facilita a busca pelo pod
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "donatowill/hello-go:v6"

          resources:
            requests: # Indica o mínimo que a aplicação precisa para rodar, ele reserva este recurso do cluster para o POD
              cpu: "0.05"
              memory: 20Mi
            limits: # O máximo que o POD pode consumir, sempre evitar que a soma de todos os limites ultrapasse a quantidade de recurso disponível no cluster
              cpu: "0.05"
              memory: 25Mi

          startupProbe:
            httpGet:
              path: /healthz
              port: 8081
            periodSeconds: 3
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
            periodSeconds: 3
            failureThreshold: 1
            # initialDelaySeconds: 10 #Informa um tempo para que aguarde antes de iniciar a verificar

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            periodSeconds: 5 #Efetua a requisição a cada 5 segundos
            failureThreshold: 1 # Limite de quanto ocorre algum problema para ele reiniciar
            timeoutSeconds: 1 #Timeout para a chamado ao endpoint de health
            successThreshold: 1 #Informa quantas vezes ele precisa testar para confirmar que o serviço está ok
            # initialDelaySeconds: 15

          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret
          volumeMounts: #Monta o volume que declaramos
            - mountPath: "/go/myfamily"
              name: config
            - mountPath: "/go/pvc"
              name: goserver-volume
      volumes: #Injetando arquivo ou valores no container
        - name: goserver-volume
          persistentVolumeClaim:
            claimName: goserver-pvc
        - name: config
          configMap:
            name: configmap-family
            items:
            - key: members
              path: "family.txt"
          # env:
          #   - name: NAME
          #     valueFrom:
          #       configMapKeyRef:
          #         name: goserver-env
          #         key: NAME
          #   - name: AGE
          #     valueFrom:
          #       configMapKeyRef:
          #         name: goserver-env
          #         key: AGE