apiVersion: v1
kind: Pod
metadata:
  name: "goserver"
  labels: #label facilita a busca pelo pod
    app: "goserver"
spec:
  containers:
    - name: goserver
      image: "donatowill/hello-go:latest"
      